version: 0
metadata:
  name: "TaskCluster GitHub Tests"
  description: "All non-integration tests for taskcluster github"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 3600
      image: 'golang:1.8'
      command:
        - /bin/bash
        - '-c'
        - >-
          go get -t github.com/taskcluster/taskcluster-cli/... 
          && cd  /go/src/github.com/taskcluster/taskcluster-cli 
          && git fetch {{ event.head.repo.url }} {{ event.head.ref }} 
          && git checkout {{ event.head.sha }} 
          && make 
          && go test ./...
          && go get -u github.com/alecthomas/gometalinter 
          && gometalinter --install
          && go get -u ./...
          && gometalinter --disable-all --enable=gotype --enable=golint 
          --enable=deadcode --enable=staticcheck --enable=deadcode 
          --enable=misspell --enable=vet --enable=vetshadow --enable=gosimple
    metadata:
      name: "TaskCluster .taskcluster.yml file"
      description: "All non-integration tests"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
