// generated by go-import-subtree -- DO NOT EDIT
package main

import _ "github.com/taskcluster/taskcluster-cli/apis"
import _ "github.com/taskcluster/taskcluster-cli/client"
import _ "github.com/taskcluster/taskcluster-cli/config"
import _ "github.com/taskcluster/taskcluster-cli/extpoints"
import _ "github.com/taskcluster/taskcluster-cli/scope"
import _ "github.com/taskcluster/taskcluster-cli/version"
